// Generated by CoffeeScript 1.4.0
(function() {

  if (typeof window !== "undefined" && window !== null) {
    this.global = window;
  }

  /* Main modules:
  */


  global.Houce = ext();

  global.models = ext();

  global.utils = ext();

  global.config = ext();

  global.Template = typeof Template !== "undefined" && Template !== null ? Template : ext();

  global.delay = function(ms, func) {
    if (Object.isFunction(ms)) {
      return ms.delay();
    } else {
      return func.delay(ms);
    }
  };

  Houce.init_houce = function(args) {
    var defaults, prev_config, v, _ref;
    if ((_ref = global.Data) == null) {
      global.Data = {};
    }
    defaults = {
      main_page: null,
      before_open_page: function() {},
      after_open_page: function() {},
      data_structure: {},
      data_version: 1,
      config: {
        storage_on: true
      },
      layout: {
        wrapper: ''
      },
      init_app: function() {},
      error_logging: false
    };
    args = merge(defaults, args);
    Pager.main_page = config.main_page || args.main_page;
    Pager.before_open_page = args.before_open_page;
    Pager.after_open_page = args.after_open_page;
    /* Error logging to server
    */

    /* Config
    */

    merge(config, args.config);
    prev_config = JSON.parse(localStorage.config || '{}');
    if (((v = prev_config.version) != null) && v === config.version) {
      merge(config, prev_config);
    }
    $(window).bind('unload', function() {
      return localStorage.config = JSON.stringify(config);
    });
    try {
      localStorage.storage_test = 'works';
      sessionStorage.storage_test = 'works';
    } catch (err) {
      config.storage_on = false;
    }
    /* Init templates
    */

    Houce.init_templates();
    /* Namespacing to store all modules under single application object
    */

    global[config.app_name] = {
      config: config,
      houce: Houce,
      models: models,
      utils: utils
    };
    /* Init application
    */

    if (!window.ERROR) {
      $('body').html(Houce.parse_template(config.layout || args.layout));
      Pager.tmpl_container = $(config.tmpl_container || args.tmpl_container || 'body');
      args.init_app();
      return Pager.start_url_checking();
    }
  };

}).call(this);
